language: python
python:
  - "3.7"

cache:
  directories:
    - $HOME/.conda/pkgs
    - $HOME/.cache/pip

install:
  - sudo apt-get update
  - wget -O miniconda.sh https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda

  # Useful for debugging any issues with conda
  - conda info -a

  # Create environment
  - conda env create -f environment.yml
  - source activate data-science-project

script:
  - flake8
  - pytest
